lint.ignore = [
    "A001",
    "A002",
    "A004",
    "A005",
    "ANN001",
    "ANN002",
    "ANN201",
    "ANN202",
    "ANN204",
    "ARG001",
    "ARG002",
    "B005",
    "B006",
    "B007",
    "B012",
    "BLE001",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D200",
    "D202",
    "D205",
    "D208",
    "D209",
    "D212",
    "D400",
    "D401",
    "D403",
    "D404",
    "D413",
    "D415",
    "DTZ003",
    "E501",
    "E721",
    "F401",
    "F841",
    "FBT002",
    "FURB101",
    "FURB103",
    "FURB154",
    "I001",
    "ISC001",
    "ISC003",
    "N802",
    "N803",
    "N806",
    "N812",
    "N816",
    "N999",
    "PERF102",
    "PERF203",
    "PERF401",
    "PIE790",
    "PLC0415",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR0917",
    "PLR1702",
    "PLR1711",
    "PLR1714",
    "PLR2004",
    "PLR6104",
    "PLR6201",
    "PLR6301",
    "PLW0127",
    "PLW0602",
    "PLW0603",
    "PLW0604",
    "PLW1514",
    "PLW2901",
    "PTH100",
    "PTH102",
    "PTH109",
    "PTH112",
    "PTH113",
    "PTH118",
    "PTH120",
    "PTH123",
    "RET502",
    "RET504",
    "RET505",
    "RUF012",
    "S101",
    "S107",
    "S110",
    "S201",
    "S301",
    "S403",
    "S701",
    "SIM102",
    "SIM103",
    "SIM105",
    "SIM108",
    "SIM114",
    "SIM118",
    "UP004",
    "UP008",
    "UP009",
    "UP010",
    "UP015",
    "UP028",
    "UP031"
]