name: Python code style check with black

on: [push]

# only one run per PR/branch happens at a time, cancelling the old run when a new one starts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  black:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: |
        sudo apt-get update && sudo apt-get install python3 python3-pip -y
    - name: Install pip dependencies
      run: |
        pip3 install black==23.1.0
    - name: Check code style with Black
      run: |
        black --check --diff --line-length 79 .
