name: Python Flake8 Code Quality

on: [push]

# only one run per PR/branch happens at a time, cancelling the old run when a new one starts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  flake8-actinia:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.8.0
    - name: Run Flake8
      run: |
        flake8 --config=.flake8 --count --statistics --show-source --jobs=$(nproc) .
