name: Post PR code suggestions

on:
  workflow_run:
    workflows: ["Linting and code quality check"]
    types:
      - completed

permissions: {}

jobs:
  post-pr-reviews:
    permissions:
      pull-requests: write
    uses: mundialis/github-workflows/.github/workflows/post-pr-reviews.yml@main