---
name: Generate Third-Party Licenses

on:
  release:
    types: [published]

jobs:
  generate-third-party-licenses:
    permissions:
      contents: write
    uses: mundialis/github-workflows/.github/workflows/third-party-licenses.yml@main
    with:
      pyproject: pyproject.toml
